import {ageResources,validateSleeveAttributes,SLEEVE_LIMITS,sleeveHealthFormula,damageThresholdFromStrength,traitCost,baggageEntryForTotal} from './rules-engine.mjs';
const SYS='altered-carbon-rpg';
async function loadJSON(path){const r=await fetch(`systems/${SYS}/data/${path}`);if(!r.ok)throw new Error(`Unable to load ${path}`);return r.json();}
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'');
function commonalityFor(archetype,tree,age){const common={Criminal:'Crime',Official:'Law and Government',Socialite:'Business and Society',Soldier:'Combat',Technician:'Technology'};const anomaly={Criminal:'Law and Government',Official:'Crime',Socialite:'Survival',Soldier:'Business and Society',Technician:'Combat'};if(tree==='Praxis'&&Number(age)>100)return'common';if(common[archetype]===tree)return'common';if(anomaly[archetype]===tree)return'anomaly';return'uncommon';}
function findTrait(catalog,[branch,name]){const b=norm(branch),n=norm(name);return catalog.find(t=>norm(t.branch)===b&&norm(t.name)===n)||catalog.find(t=>norm(t.name)===n&&(norm(t.branch).includes(b)||b.includes(norm(t.branch))));}
async function rollTotal(formula){if(!formula||formula==='0')return 0;return Number((await new Roll(formula).evaluate()).total||0);}

export class ACCharacterCreator extends foundry.applications.api.HandlebarsApplicationMixin(foundry.applications.api.ApplicationV2){
 static DEFAULT_OPTIONS={id:'ac-character-creator',window:{title:'Altered Carbon — Character Creator'},position:{width:700,height:780},actions:{create:this._create}};
 static PARTS={main:{template:'systems/altered-carbon-rpg/templates/character-creator.hbs'}};
 async _prepareContext(options){const context=await super._prepareContext(options),ref=await loadJSON('archetype-reference.json');const archetypes=Object.keys(ref.archetypes),packageOptions=[];for(const [a,data] of Object.entries(ref.archetypes))for(const p of Object.keys(data.packages))packageOptions.push({value:`${a}::${p}`,label:`${a} — ${p}`});return{...context,archetypes,sleeveTypes:Object.keys(SLEEVE_LIMITS).filter(x=>x!=='other'),packageOptions};}
 static async _create(){
   const q=n=>this.element.querySelector(`[name="${n}"]`)?.value;
   const name=q('name')?.trim()||'New DHF',archetype=q('archetype')||'Civilian',variant=q('variant')||'standard',age=variant==='ai'?0:Math.max(18,Number(q('age')||30)),sleeveType=q('sleeveType')||'birth',packageChoice=q('package')||'';
   if(packageChoice&&packageChoice.split('::')[0]!==archetype)return ui.notifications.error('The selected Starting Package must belong to the selected Archetype.');
   if(variant==='ai'&&archetype==='Soldier')return ui.notifications.error('AI characters cannot use the Soldier Archetype under the 2020 Core rules.');
   if(variant==='ai'&&!String(sleeveType).startsWith('synthetic-'))return ui.notifications.error('The guided AI creator requires a synthetic sleeve. AI may otherwise operate from a building/mainframe, but that is created manually as an AI Actor.');
   const attrs={strength:Number(q('strength')||30),perception:Number(q('perception')||30),empathy:Number(q('empathy')||30),willpower:Number(q('willpower')||30),acuity:Number(q('acuity')||30),intelligence:Number(q('intelligence')||30)};
   const validation=validateSleeveAttributes(sleeveType,attrs);if(!validation.valid)return ui.notifications.error(`Sleeve attributes outside ${sleeveType} limits: STR ${validation.limits.strength.join('–')}, PER ${validation.limits.perception.join('–')}.`);
   if(['empathy','willpower','acuity','intelligence'].some(k=>attrs[k]<30||attrs[k]>50))return ui.notifications.error('Starting Stack Attributes must be between 30 and 50 before cap-altering Traits. Values above 30 are treated as a pre-generated/GM-authored final allocation; use the Actor advancement API for rolled SP increases during play.');
   let starting=variant==='ai'?null:ageResources(age,attrs);if(variant==='ai'){const spRaw=q('manualSP'),ipRaw=q('manualIP');if(spRaw===''||ipRaw==='')return ui.notifications.error('The 2020 Core gives AI no age-based starting SP/IP row. Enter explicit AI Stack Points and Influence Points rather than using an invented default.');starting={stackPoints:Math.max(0,Number(spRaw)),egoPoints:attrs.willpower,influencePoints:Math.max(0,Number(ipRaw)),baggageDice:0,lifeEventRolls:0};}if(variant==='religious'&&age<=40)starting.stackPoints+=25;const [skills,presets,archetypeRef,traitsData,baggageData]=await Promise.all([loadJSON('core-skills.json'),loadJSON('archetype-skills.json'),loadJSON('archetype-reference.json'),loadJSON('trait-catalog.json'),loadJSON('baggage-catalog.json')]);
   const preset=presets.archetypes[archetype]||presets.archetypes.Civilian,levelById=new Map(preset.map(x=>[x.id,x.level]));
   const hp=await rollTotal(sleeveHealthFormula(sleeveType,attrs.strength)),threshold=damageThresholdFromStrength(attrs.strength);let ep=starting.egoPoints,ip=starting.influencePoints;
   const extra={Civilian:'1d6',Criminal:'1d8',Soldier:'1d10'}[archetype];if(extra)ep+=await rollTotal(extra);if(archetype==='Official')ip+=1;if(archetype==='Socialite')ip+=2;if(variant==='meth')ip+=2;
   const archetypeData=archetypeRef.archetypes[archetype],wealth=Number(q('wealth')||archetypeData?.wealth||1);
   const actorType=variant==='ai'?'ai':'character';const backup=variant==='meth'?{enabled:true,priceLevel:4,routine:false,notes:'Meth starting backup — lower-tier source default.'}:undefined;const actor=await Actor.create({name,type:actorType,ownership:{default:0,[game.user.id]:3},system:{identity:{trueName:name,publicName:name,dhfAge:age,storageYears:0,archetype,variant},attributes:attrs,resources:{health:{value:hp,max:hp},ego:{value:ep,max:ep},wounds:{value:0,max:threshold},stackPoints:{value:starting.stackPoints,max:starting.stackPoints},influence:{value:ip,max:ip}},wealth,stackState:'intact',sleeveState:'healthy',...(backup?{backup}:{})}});
   const items=[{name:`${name} — Starting Sleeve`,type:'sleeve',system:{status:'active',sleeveType,strength:attrs.strength,perception:attrs.perception,healthMax:hp,damageThreshold:threshold,techCapacity:validation.limits.techCapacity,geoRestricted:variant==='ai',rulesRef:'Core Rulebook 2020, Chapter 2: Sleeves'}},...skills.map(s=>({name:s.name,type:'skill',system:{catalogId:s.id,attribute:s.attribute,level:levelById.get(s.id)||1,rulesRef:s.rulesRef,rulesText:s.rulesText||''}}))];
   if(packageChoice){const packageName=packageChoice.split('::')[1],pkg=archetypeData.packages[packageName];for(const spec of pkg.traits||[]){const t=findTrait(traitsData.traits,spec);if(!t)continue;const commonality=commonalityFor(archetype,t.tree,age);items.push({name:t.name,type:'trait',system:{catalogId:t.id,tree:t.tree,branch:t.branch,tier:t.tier,commonality,spCost:0,effect:t.effect,description:t.effect,rulesRef:t.rulesRef}});}items.push({name:`Starting Package — ${packageName}`,type:'equipment',system:{description:`<p>${pkg.gear}</p>`,rulesRef:'Core Rulebook 2020, Archetype Starting Package'}});}
   if(variant!=='standard')items.push({name:`Variant — ${variant}`,type:'equipment',system:{description:`<p>Advanced variant selected. Open the 2020 Rules Reference for all mandatory rules and choice-based benefits. Runtime-enforced invariants are applied where deterministic; choice-based Traits/benefits remain explicit player/GM selections.</p>`,rulesRef:'Core Rulebook 2020, Variant Characters'}});
   for(let i=0;i<starting.lifeEventRolls;i++){const roll=await new Roll(`${starting.baggageDice}d6`).evaluate(),b=baggageEntryForTotal(baggageData,roll.total);if(b)items.push({name:b.name,type:'baggage',system:{catalogId:b.id,rollMin:b.min,rollMax:Number.isFinite(b.max)?b.max:999,appliesTo:b.sleeveOrStack?'Sleeve or Stack':'Narrative',description:b.effect,rulesRef:b.rulesRef}});}
   await actor.createEmbeddedDocuments('Item',items);
   ui.notifications.info(`${name} created: ${starting.stackPoints} SP, ${ep} EP, ${ip} IP, ${hp} HP; ${starting.lifeEventRolls} Baggage roll(s) resolved.`);actor.sheet.render(true);this.close();
 }
}
