const {BooleanField, HTMLField, NumberField, SchemaField, StringField} = foundry.data.fields;
const N=(opts={})=>new NumberField({required:true, integer:true, initial:0, ...opts});
const S=(opts={})=>new StringField({required:true, blank:true, initial:'', ...opts});
const H=()=>new HTMLField({required:true, blank:true, initial:''});
const resource=(initial=0)=>new SchemaField({value:N({min:0,initial}),max:N({min:0,initial})});
const attrs=()=>new SchemaField({strength:N({min:0,max:150,initial:30}),perception:N({min:0,max:150,initial:30}),empathy:N({min:0,max:150,initial:30}),willpower:N({min:0,max:150,initial:30}),acuity:N({min:0,max:150,initial:30}),intelligence:N({min:0,max:150,initial:30})});

class BaseActorModel extends foundry.abstract.TypeDataModel {
 static defineSchema(){return {
   biography:H(),
   identity:new SchemaField({trueName:S(),publicName:S(),pronouns:S(),sleevePronouns:S(),dhfAge:N({min:0}),storageYears:N({min:0}),archetype:S(),variant:S({initial:'standard'}),currentObjective:S()}),
   attributes:attrs(),
   resources:new SchemaField({health:resource(10),ego:resource(20),wounds:resource(0),stackPoints:resource(0),influence:resource(0)}),
   wealth:N({min:0,max:6,initial:2}),
   economy:new SchemaField({deferral:N({min:0,max:5,initial:0}),debt:new BooleanField({required:true,initial:false})}),
   backup:new SchemaField({enabled:new BooleanField({required:true,initial:false}),priceLevel:N({min:0,max:6,initial:0}),routine:new BooleanField({required:true,initial:false}),notes:S()}),
   egoState:new StringField({required:true,choices:['stable','damaged','critical','splintered'],initial:'stable'}),
   stackState:new StringField({required:true,choices:['intact','damaged','destroyed'],initial:'intact'}),
   sleeveState:new StringField({required:true,choices:['healthy','dying','stable','dead','awaiting-resleeving'],initial:'healthy'}),
   defense:N({min:0}), speedModifier:N({initial:0}), notes:S()
 };}
}
export class CharacterModel extends BaseActorModel {}
export class NPCModel extends BaseActorModel {static defineSchema(){return {...super.defineSchema(),secrets:new SchemaField({trueIdentity:S(),actualAllegiance:S(),presentedAllegiance:S(),agenda:H(),recognitionState:S({initial:'unknown'})})};}}
export class ThreatModel extends BaseActorModel {static defineSchema(){return {...super.defineSchema(),morale:N({min:0,max:10,initial:5}),tactics:H(),minionBonus:N({min:0}),nemesis:new BooleanField({required:true,initial:false})};}}
export class AIModel extends BaseActorModel {static defineSchema(){return {...super.defineSchema(),construct:new SchemaField({systems:H(),assets:H(),permissions:H(),directives:H(),virtualNative:new BooleanField({required:true,initial:true})})};}}
export class VehicleModel extends BaseActorModel {static defineSchema(){return {...super.defineSchema(),vehicle:new SchemaField({size:N({min:0,initial:1}),durability:N({min:0,initial:10}),structure:resource(2),velocity:S(),speedDice:N({min:0,initial:2}),fuel:resource(5),crewSkeleton:N({min:0,initial:1}),crewStandard:N({min:0,initial:1}),crewFull:N({min:0,initial:1}),handling:N({min:0,initial:1}),fireControl:N({min:0}),travel:S({initial:'district'}),cargo:N({min:0}),passengers:N({min:0}),systems:H()})};}}

class BaseItemModel extends foundry.abstract.TypeDataModel {static defineSchema(){return {description:H(),rulesRef:S(),catalogId:S()};}}
export class SleeveModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),sleeveType:new StringField({required:true,choices:['birth','natal','clone','synthetic-low','synthetic-mid','synthetic-high','organic','other'],initial:'organic'}),status:new StringField({required:true,choices:['candidate','active','archived','lost','destroyed','dead','stored'],initial:'candidate'}),quality:S(),sex:S(),pronouns:S(),apparentAge:N({min:0}),strength:N({min:0,max:150,initial:30}),perception:N({min:0,max:150,initial:30}),healthMax:N({min:0,initial:10}),damageThreshold:N({min:0,initial:30}),techCapacity:N({min:0}),techUsed:N({min:0}),acquired:S(),lost:S(),lossCause:S(),acquisitionSource:S(),appearance:H(),complications:H(),compulsoryTransfer:new BooleanField({required:true,initial:false}),crossSleeved:new BooleanField({required:true,initial:false}),preferredBirthClone:new BooleanField({required:true,initial:false}),geoRestricted:new BooleanField({required:true,initial:false}),lowQuality:new BooleanField({required:true,initial:false}),syntheticFeatureCount:N({min:0,initial:0})};}}
export class ArchivedSleeveModel extends SleeveModel {}
export class SkillModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),level:N({min:1,max:5,initial:1}),attribute:new StringField({required:true,choices:['strength','perception','empathy','willpower','acuity','intelligence'],initial:'acuity'}),trainingBonus:N({initial:0}),specialisations:S(),rulesText:H()};}}
export class TraitModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),tree:S(),branch:S(),tier:N({min:1,max:5,initial:1}),commonality:new StringField({required:true,choices:['common','uncommon','anomaly'],initial:'uncommon'}),spCost:N({min:0}),trigger:H(),effect:H()};}}
export class SpecialisationModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),skill:S(),missingDifficulty:N({min:0})};}}
class GearItemModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),priceLevel:N({min:0,max:6}),techPoints:N({min:0}),techUsed:N({min:0}),cargoUnits:N({min:0}),partialCargo:N({min:0}),heavy:N({min:0}),bodySlots:S(),powered:new BooleanField({required:true,initial:false}),specialRules:S()};}}
export class WeaponModel extends GearItemModel {static defineSchema(){return {...super.defineSchema(),skill:S({initial:'firearms'}),damage:S(),damageType:S(),complexity:N({min:1,initial:2}),range:S(),capacity:N({min:0}),depletion:N({min:0}),depletionMode:new StringField({required:true,choices:['check','counter','none'],initial:'check'}),depletionFormula:S({initial:'1'}),exhausted:new BooleanField({required:true,initial:false}),gearBonus:N({initial:0}),bonusDice:S(),accuracy:N({min:0}),armorPiercing:new BooleanField({required:true,initial:false}),deadly:N({min:0}),firingMode:S({initial:'semi-automatic'}),triggeredEffects:H(),upgrades:H()};}}
export class ArmourModel extends GearItemModel {static defineSchema(){return {...super.defineSchema(),defense:N({min:0}),protection:N({min:0}),damageTypes:S(),layering:new BooleanField({required:true,initial:false}),battleArmor:new BooleanField({required:true,initial:false}),upgrades:H()};}}
export class EquipmentModel extends GearItemModel {static defineSchema(){return {...super.defineSchema(),capacity:N({min:0}),depletion:N({min:0}),depletionMode:new StringField({required:true,choices:['check','counter','none'],initial:'check'}),depletionFormula:S({initial:'1'}),exhausted:new BooleanField({required:true,initial:false}),gearBonus:N({initial:0}),bonusDice:S(),upgrades:H()};}}
export class AugmentationModel extends GearItemModel {static defineSchema(){return {...super.defineSchema(),techCost:N({min:0}),active:new BooleanField({required:true,initial:true}),upgrades:H()};}}
export class BaggageModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),rollMin:N({min:0}),rollMax:N({min:0}),severity:N({min:0,max:10}),appliesTo:S(),resolved:new BooleanField({required:true,initial:false})};}}
export class ConditionModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),key:S(),category:S(),difficulty:N({initial:0}),severity:N({min:0,initial:0}),duration:S(),stacking:new BooleanField({required:true,initial:false})};}}
export class InjuryModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),key:S(),count:N({min:1,initial:1}),recoveryRate:S(),active:new BooleanField({required:true,initial:true})};}}
export class ScandalModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),key:S(),active:new BooleanField({required:true,initial:true}),influenceLoss:N({min:0})};}}
export class NetworkModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),organization:S(),level:N({min:1,max:5,initial:1}),requestBonus:N({initial:0}),exhausted:new BooleanField({required:true,initial:false}),categories:S()};}}
export class ResourceEntryModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),priceLevel:N({min:0,max:6}),capacity:N({min:0}),depletion:N({min:0}),rare:new BooleanField({required:true,initial:false}),regulated:new BooleanField({required:true,initial:false}),unregistered:new BooleanField({required:true,initial:false}),grayMarket:new BooleanField({required:true,initial:false}),blackMarket:new BooleanField({required:true,initial:false}),exhausted:new BooleanField({required:true,initial:false}),itemName:S()};}}
export class RelationshipModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),secret:H(),pcId:S(),pcSleeveId:S(),contactId:S(),contactHistoricalIdentity:S(),category:new StringField({required:true,choices:['enemy','rival','ally','loved-one'],initial:'ally'}),historicalIncident:H(),currentAlias:S(),presentAgenda:H(),recognitionClues:H(),evidence:H(),revealState:new StringField({required:true,choices:['unknown','familiar','suspected','confirmed','deceptive','hostile','reconciled'],initial:'unknown'}),plotCritical:new BooleanField({required:true,initial:false})};}}
export class ClueModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),secret:H(),revelationId:S(),essential:new BooleanField({required:true,initial:false}),verified:new BooleanField({required:true,initial:false})};}}
export class MemoryModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),secret:H(),year:N({min:0}),sleeveId:S(),recovered:new BooleanField({required:true,initial:false})};}}
export class CreditSetModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),value:N({min:0,max:6}),spent:N({min:0}),untraceable:new BooleanField({required:true,initial:false})};}}
export class SoftwareModel extends GearItemModel {static defineSchema(){return {...super.defineSchema(),capacity:N({min:0}),depletion:N({min:0}),depletionMode:new StringField({required:true,choices:['check','counter','none'],initial:'check'}),depletionFormula:S({initial:'1'}),exhausted:new BooleanField({required:true,initial:false}),triggeredEffects:H()};}}
export class VirtualConstructModel extends BaseItemModel {static defineSchema(){return {...super.defineSchema(),integrity:N({min:0}),accessLevel:N({min:0}),firewallClass:S(),virusClass:S()};}}
