import {rollSkill} from './rolls.mjs';
import {createOpposedChallenge} from './opposed.mjs';
import {ACRulesBrowser} from './rules-browser.mjs';
import {useWeapon,useEquipment} from './chat-actions.mjs';
const {api,sheets}=foundry.applications;const {HandlebarsApplicationMixin}=api;

const ITEM_FIELDS={
 sleeve:[['sleeveType','Sleeve Type','text'],['status','Status','text'],['quality','Quality','text'],['sex','Sex','text'],['pronouns','Sleeve Pronouns','text'],['apparentAge','Apparent Age','number'],['strength','Strength','number'],['perception','Perception','number'],['healthMax','Health Maximum','number'],['damageThreshold','Damage Threshold (derived = Strength)','number'],['techCapacity','Tech Capacity','number'],['techUsed','Tech Used','number'],['acquired','Acquired','text'],['lost','Lost','text'],['lossCause','Loss / Transfer Cause','text'],['acquisitionSource','Acquisition Source','text'],['appearance','Appearance','textarea'],['complications','Complications','textarea'],['compulsoryTransfer','Compulsory / Uncontrolled Transfer','checkbox'],['crossSleeved','Diverges from DHF Self-Image','checkbox'],['preferredBirthClone','Clone of Own Birth Sleeve','checkbox'],['geoRestricted','GeoRestriction Feature','checkbox'],['lowQuality','Low Quality Synthetic','checkbox'],['syntheticFeatureCount','Synthetic Feature Count','number']],
 archivedSleeve:[['sleeveType','Sleeve Type','text'],['status','Status','text'],['sex','Sex','text'],['strength','Strength','number'],['perception','Perception','number'],['healthMax','Health Maximum','number'],['damageThreshold','Damage Threshold','number'],['acquired','Acquired','text'],['lost','Lost','text'],['lossCause','Loss / Transfer Cause','text'],['appearance','Appearance','textarea'],['complications','Complications','textarea'],['compulsoryTransfer','Compulsory / Uncontrolled Transfer','checkbox'],['crossSleeved','Diverges from DHF Self-Image','checkbox'],['preferredBirthClone','Clone of Own Birth Sleeve','checkbox'],['geoRestricted','GeoRestriction Feature','checkbox'],['lowQuality','Low Quality Synthetic','checkbox'],['syntheticFeatureCount','Synthetic Feature Count','number']],
 skill:[['level','Skill Level','number'],['attribute','Primary Attribute','text'],['trainingBonus','Training Value','number'],['specialisations','Specialisations','text'],['rulesText','2020 Rules Reference','textarea']],
 trait:[['tree','Trait Tree','text'],['branch','Branch','text'],['tier','Tier','number'],['commonality','Commonality','text'],['spCost','SP Cost','number'],['effect','Mechanical Effect','textarea'],['trigger','Trigger / Note','textarea']],
 specialisation:[['skill','Skill','text'],['missingDifficulty','Untrained Difficulty','number']],
 weapon:[['skill','Skill','text'],['damage','Damage','text'],['damageType','Damage Type','text'],['complexity','Action Complexity','number'],['range','Range','text'],['priceLevel','Price Level','number'],['techPoints','Tech Points','number'],['techUsed','Tech Used','number'],['cargoUnits','Cargo Units','number'],['heavy','Heavy','number'],['bodySlots','Body Slots','text'],['powered','Powered','checkbox'],['specialRules','Special Rules','text'],['capacity','Capacity','number'],['depletion','Depletion Points','number'],['depletionMode','Depletion Mode (check/counter/none)','text'],['depletionFormula','DP per Use Formula','text'],['exhausted','Exhausted','checkbox'],['gearBonus','Gear Bonus','number'],['bonusDice','Bonus Dice','text'],['accuracy','Accuracy','number'],['armorPiercing','Armor Piercing','checkbox'],['deadly','Deadly','number'],['firingMode','Firing Mode','text'],['triggeredEffects','Triggered Effects','textarea'],['upgrades','Upgrades','textarea']],
 armour:[['priceLevel','Price Level','number'],['techPoints','Tech Points','number'],['cargoUnits','Cargo Units','number'],['heavy','Heavy','number'],['bodySlots','Body Slots','text'],['defense','Defense','number'],['protection','Protection','number'],['damageTypes','Applicable Damage Types','text'],['layering','Layering','checkbox'],['battleArmor','Battle Armor','checkbox'],['specialRules','Special Rules','text'],['upgrades','Upgrades','textarea']],
 equipment:[['priceLevel','Price Level','number'],['techPoints','Tech Points','number'],['techUsed','Tech Used','number'],['cargoUnits','Cargo Units','number'],['heavy','Heavy','number'],['bodySlots','Body Slots','text'],['powered','Powered','checkbox'],['specialRules','Special Rules','text'],['capacity','Capacity','number'],['depletion','Depletion Points','number'],['depletionMode','Depletion Mode (check/counter/none)','text'],['depletionFormula','DP per Use Formula','text'],['exhausted','Exhausted','checkbox'],['gearBonus','Gear Bonus','number'],['bonusDice','Bonus Dice','text'],['upgrades','Upgrades','textarea']],
 augmentation:[['priceLevel','Price Level','number'],['techCost','Tech Cost','number'],['techPoints','Tech Points','number'],['techUsed','Tech Used','number'],['powered','Powered','checkbox'],['active','Active','checkbox'],['specialRules','Special Rules','text'],['upgrades','Upgrades','textarea']],
 baggage:[['rollMin','Roll Minimum','number'],['rollMax','Roll Maximum','number'],['severity','Severity','number'],['appliesTo','Applies To','text'],['resolved','Resolved','checkbox']],
 condition:[['key','Condition Key','text'],['category','Category','text'],['difficulty','Difficulty','number'],['severity','Severity / Mechanical Level','number'],['duration','Duration','text'],['stacking','Stacks','checkbox']],
 injury:[['key','Injury Key','text'],['count','Count','number'],['recoveryRate','Recovery Rate','text'],['active','Active','checkbox']],
 scandal:[['key','Scandal Key','text'],['active','Active','checkbox'],['influenceLoss','Influence Loss','number']],
 network:[['organization','Organization','text'],['level','Request Level','number'],['requestBonus','Request Bonus','number'],['categories','Categories','text'],['exhausted','Exhausted','checkbox']],
 resourceEntry:[['itemName','Item / Service','text'],['priceLevel','Price Level','number'],['capacity','Capacity','number'],['depletion','Depletion','number'],['rare','Rare','checkbox'],['regulated','Regulated','checkbox'],['unregistered','Unregistered','checkbox'],['grayMarket','Gray Market','checkbox'],['blackMarket','Black Market / Custom','checkbox'],['exhausted','Exhausted','checkbox']],
 relationship:[['category','Category','text'],['revealState','Reveal State','text'],['historicalIncident','Historical Incident','textarea'],['recognitionClues','Recognition Clues','textarea'],['contactHistoricalIdentity','Historical Identity','text'],['presentAgenda','Present Agenda','textarea',true]],
 clue:[['revelationId','Revelation ID','text'],['essential','Essential','checkbox'],['verified','Verified','checkbox'],['secret','GM Secret','textarea',true]],
 memory:[['year','Year','number'],['sleeveId','Sleeve ID','text'],['recovered','Recovered','checkbox'],['secret','Private / GM Note','textarea']],
 creditSet:[['value','Credit Level','number'],['spent','Spent','number'],['untraceable','Untraceable','checkbox']],
 software:[['priceLevel','Price Level','number'],['techPoints','Tech Points','number'],['powered','Powered','checkbox'],['capacity','Capacity','number'],['depletion','Depletion Points','number'],['depletionMode','Depletion Mode (check/counter/none)','text'],['depletionFormula','DP per Use Formula','text'],['exhausted','Exhausted','checkbox'],['triggeredEffects','Triggered Effects','textarea']],
 virtualConstruct:[['integrity','Integrity','number'],['accessLevel','Access Level','number'],['firewallClass','Firewall Class','text'],['virusClass','Virus Class','text']]
};

async function checkOptionsDialog(skill,defaults={}){
 const content=`<div class="form-group"><label>Difficulty</label><input type="number" name="difficulty" value="${Number(defaults.difficulty||0)}"></div><div class="form-group"><label>Other / Stackable TR Bonus</label><input type="number" name="bonus" value="${Number(defaults.bonus||0)}"></div><div class="form-group"><label>Gear Bonus</label><input type="number" name="gearBonus" value="${Number(defaults.gearBonus||0)}"></div><div class="form-group"><label>Bonus Dice (comma sides, e.g. 8,8)</label><input name="bonusDice" value="${String(defaults.bonusDice||'')}"></div><div class="form-group"><label>Luck Die</label><select name="luckSides"><option value="">None</option><option>12</option><option>10</option><option>8</option><option>6</option><option>4</option></select></div><div class="form-group"><label>Luck Mode</label><select name="luckMode"><option value="none">None</option><option value="beginners">Beginner's Luck</option><option value="pressing">Pressing Their Luck</option><option value="making">Making Their Own Luck</option><option value="tough">Tough Luck</option><option value="dumb">Dumb Luck — decide after roll</option></select></div><div class="form-group"><label><input type="checkbox" name="sightReliant"> Sight-reliant check (Dazzled)</label></div><div class="form-group"><label><input type="checkbox" name="sightOnly"> Sight-only check (Dazzled)</label></div><div class="form-group"><label>Visibility</label><select name="rollMode"><option value="publicroll">Public</option><option value="gmroll">GM + You</option><option value="blindroll">Blind to GM</option><option value="selfroll">Self</option></select></div>`;
 const form=await api.DialogV2.input({window:{title:`${skill.name} Check`},content});if(!form)return null;const get=k=>form instanceof FormData?form.get(k):form?.[k];
 return {difficulty:Number(get('difficulty')||0),bonus:Number(get('bonus')||0),gearBonus:Number(get('gearBonus')||0),bonusDice:String(get('bonusDice')||'').split(',').map(x=>Number(x.trim())).filter(x=>[4,6,8,10,12].includes(x)),luckSides:get('luckSides')?Number(get('luckSides')):null,luckMode:get('luckMode')||'none',sightReliant:Boolean(get('sightReliant')),sightOnly:Boolean(get('sightOnly')),rollMode:get('rollMode')||'publicroll'};
}

export class ACActorSheet extends HandlebarsApplicationMixin(sheets.ActorSheetV2){
 static DEFAULT_OPTIONS={classes:['altered-carbon','actor-sheet'],position:{width:900,height:800},form:{closeOnSubmit:false},actions:{rollSkill:this._rollSkill,opposedRoll:this._opposedRoll,useWeapon:this._useWeapon,useEquipment:this._useEquipment,addDepletion:this._addDepletion,activateSleeve:this._activateSleeve,spendSP:this._spendSP,openCombat:this._openCombat,openRules:this._openRules,editItem:this._editItem,setTab:this._setTab}};
 static PARTS={main:{template:'systems/altered-carbon-rpg/templates/actor-sheet.hbs'}};
 _tab='identity';
 async _prepareContext(options){
   const context=await super._prepareContext(options),actor=this.actor,tab=this._tab||'identity';
   const all=actor.items.contents;
   return {...context,actor,system:actor.system,ac:actor.ac,tab,
     isIdentity:tab==='identity',isSleeve:tab==='sleeve',isSkills:tab==='skills',isTraits:tab==='traits',isHistory:tab==='history',isRelationships:tab==='relationships',isEvidence:tab==='evidence',isGear:tab==='gear',isCombat:tab==='combat',
     skills:all.filter(i=>i.type==='skill').sort((a,b)=>a.system.attribute.localeCompare(b.system.attribute)||a.name.localeCompare(b.name)),
     sleeves:all.filter(i=>i.type==='sleeve').map(i=>({id:i.id,name:i.name,system:i.system,isActive:i.system.status==='active'})),
     archivedSleeves:all.filter(i=>i.type==='archivedSleeve').sort((a,b)=>String(a.system.acquired).localeCompare(String(b.system.acquired))),
     traits:all.filter(i=>i.type==='trait'),specialisations:all.filter(i=>i.type==='specialisation'),baggage:all.filter(i=>i.type==='baggage'),conditions:all.filter(i=>i.type==='condition'),injuries:all.filter(i=>i.type==='injury'),scandals:all.filter(i=>i.type==='scandal'),networks:all.filter(i=>i.type==='network'),resources:all.filter(i=>i.type==='resourceEntry'),
     relationships:all.filter(i=>i.type==='relationship'),clues:all.filter(i=>['clue','memory'].includes(i.type)),equipment:all.filter(i=>['weapon','armour','equipment','augmentation','software','creditSet','virtualConstruct'].includes(i.type)).map(i=>({id:i.id,name:i.name,type:i.type,system:i.system,canUse:i.type==='weapon',canUseEquipment:['equipment','software'].includes(i.type),canDeplete:['weapon','equipment','software'].includes(i.type)}))};
 }
 static async _rollSkill(event,target){const skill=this.actor.items.get(target.dataset.itemId);if(!skill)return;const opts=await checkOptionsDialog(skill);if(opts)await rollSkill(this.actor,skill,opts);}
 static async _opposedRoll(event,target){const skill=this.actor.items.get(target.dataset.itemId);if(!skill)return;const opts=await checkOptionsDialog(skill);if(!opts)return;const token=[...game.user.targets][0];await createOpposedChallenge(this.actor,skill,{...opts,targetActor:token?.actor||null});}
 static async _useWeapon(event,target){const weapon=this.actor.items.get(target.dataset.itemId);if(!weapon||weapon.type!=='weapon')return;const skill=this.actor.items.find(i=>i.type==='skill'&&(String(i.system.catalogId||'').toLowerCase()===String(weapon.system.skill||'').toLowerCase()||i.name.toLowerCase()===String(weapon.system.skill||'').replace(/-/g,' ').toLowerCase()));if(!skill)return ui.notifications.warn(`No matching Skill found for ${weapon.system.skill||weapon.name}.`);const opts=await checkOptionsDialog(skill,{gearBonus:weapon.system.gearBonus,bonusDice:weapon.system.bonusDice});if(opts)await useWeapon(this.actor,weapon,opts);}
 static async _useEquipment(event,target){const item=this.actor.items.get(target.dataset.itemId);if(!item||!['equipment','software'].includes(item.type))return;const skills=this.actor.items.filter(i=>i.type==='skill').sort((a,b)=>a.name.localeCompare(b.name));if(!skills.length)return ui.notifications.warn('This Actor has no Skills to use with the equipment.');const options=skills.map(s=>`<option value="${s.id}">${foundry.utils.escapeHTML(s.name)} (d${s.skillDieSides})</option>`).join('');const form=await api.DialogV2.input({window:{title:`Use ${item.name}`},content:`<div class="form-group"><label>Skill Check used with this equipment</label><select name="skill">${options}</select></div>`});if(!form)return;const id=form instanceof FormData?form.get('skill'):form?.skill;const skill=this.actor.items.get(id);if(!skill)return;const opts=await checkOptionsDialog(skill,{gearBonus:item.system.gearBonus,bonusDice:item.system.bonusDice});if(opts)await useEquipment(this.actor,item,skill,opts);}
 static async _addDepletion(event,target){const item=this.actor.items.get(target.dataset.itemId);if(!item)return;const amount=await api.DialogV2.prompt({window:{title:`Add Depletion — ${item.name}`},content:'<div class="form-group"><label>DP</label><input type="number" name="amount" min="0" value="1"></div>',ok:{label:'Add DP',callback:(event,button,dialog)=>Number(dialog.element.querySelector('[name=amount]')?.value||1)}});if(amount!=null)await item.addDepletion(amount);}
 static async _activateSleeve(event,target){const ok=await api.DialogV2.confirm({window:{title:'Activate Sleeve'},content:'<p>Archive the current sleeve and activate this sleeve? Core resleeving psychological effects will be applied when determinable from the sleeve records.</p>'});if(ok){const r=await this.actor.activateSleeve(target.dataset.itemId);if(r.consequences?.egoLoss||r.consequences?.stackLoss)ui.notifications.warn(`Resleeving cost: ${r.consequences.egoLoss} EP and ${r.consequences.stackLoss} SP.`);}}
 static async _openCombat(){game.alteredCarbon.openCombatConsole();}
 static async _openRules(){new ACRulesBrowser({actorId:this.actor.id}).render({force:true});}
 static async _setTab(event,target){this._tab=target.dataset.tab||'identity';this.render({force:true});}
 static async _spendSP(){const amount=await api.DialogV2.prompt({window:{title:'Spend Stack Points'},content:'<div class="form-group"><label>Amount</label><input type="number" name="amount" min="1" value="1"></div>',ok:{label:'Spend',callback:(event,button,dialog)=>Number(dialog.element.querySelector('[name=amount]')?.value||1)}});if(amount)await this.actor.spendStackPoints(amount);}
 static async _editItem(event,target){this.actor.items.get(target.dataset.itemId)?.sheet?.render(true);}
}

export class ACItemSheet extends HandlebarsApplicationMixin(sheets.ItemSheetV2){
 static DEFAULT_OPTIONS={classes:['altered-carbon','item-sheet'],position:{width:700,height:760},form:{closeOnSubmit:false}};
 static PARTS={main:{template:'systems/altered-carbon-rpg/templates/item-sheet.hbs'}};
 async _prepareContext(options){const context=await super._prepareContext(options),item=this.item;const defs=(ITEM_FIELDS[item.type]||[]).filter(([, , ,gmOnly])=>!gmOnly||game.user.isGM);const fields=defs.map(([path,label,type])=>({path:`system.${path}`,label,type,value:foundry.utils.getProperty(item.system,path),isNumber:type==='number',isCheckbox:type==='checkbox',isTextarea:type==='textarea'}));return{...context,item,system:item.system,fields};}
}
